VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Sheet6"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Sub Worksheet_Activate()
'Sheets("Non PRB Dematic Open Cases").Unprotect Password:="hhc"
'Call ptRefresh
'Sheets("Non PRB Dematic Open Cases").Protect Password:="hhc"

End Sub



Private Sub Worksheet_Change(ByVal Target As Range)
'Application.EnableEvents = False
'Call ptRefresh
'Application.EnableEvents = True

End Sub
